version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - GO_ENV=dev
      - DATABASE_URL=postgres://postgres:postgres@localhost:5432/conference-manager-db?sslmode=disable
    depends_on:
      - conference-manager-db
      - localstack

  conference-manager-db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: conference-manager-db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
      - "4572:4572"
    environment:
      - SERVICES=s3
      - DEFAULT_REGION=us-east-1
    volumes:
      - localstack_data:/var/lib/localstack

volumes:
  db_data:
  localstack_data:
