app = 'conference-manager-api'
primary_region = 'waw'

[build]

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  
[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
