#!/bin/bash

source .env
source .env.dev


AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY AWS_DEFAULT_REGION=$AWS_REGION aws --endpoint-url=$AWS_ENDPOINT_URL_S3 s3 mb s3://$AWS_BUCKETS_CONFERENCE_FILES

AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY AWS_DEFAULT_REGION=$AWS_REGION aws --endpoint-url=$AWS_ENDPOINT_URL_S3 s3 cp ./scripts/s3_mock_data/conference-files/ s3://$AWS_BUCKETS_CONFERENCE_FILES/ --recursive
